[[pages]]
path = "app.py"
name = "List of portfolios"
icon = ":basketball:"

[[pages]]
path = "pages/portfolioInfo.py"
name = "Information of portfolio"
icon = ":question:"

[[pages]]
path = "pages/about.py"
name = "About program"
icon = ":question:"
